"""Initial schema

Revision ID: 54b86edcab2f
Revises: 
Create Date: 2026-07-07 10:44:08.495062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b86edcab2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('tg_username', sa.String(length=80), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_tg_username'), ['tg_username'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('group_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('vendor', sa.String(length=120), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('compound', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('lab_test_details', sa.JSON(), nullable=True),
    sa.Column('total_lab_cost', sa.Float(), nullable=False),
    sa.Column('shipping_cost', sa.Float(), nullable=False),
    sa.Column('order_number', sa.String(length=100), nullable=True),
    sa.Column('quote_number', sa.String(length=100), nullable=True),
    sa.Column('results_link', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('refund_per_donor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_tests_status'), ['status'], unique=False)

    op.create_table('participations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_test_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('tg_username', sa.String(length=80), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('order_status', sa.String(length=50), nullable=True),
    sa.Column('us_based', sa.Boolean(), nullable=True),
    sa.Column('vial_donor', sa.Boolean(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('pay_vial_collector', sa.Boolean(), nullable=True),
    sa.Column('pay_lab', sa.Boolean(), nullable=True),
    sa.Column('paid_lab', sa.Boolean(), nullable=True),
    sa.Column('amount_owed', sa.Float(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_test_id'], ['group_tests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_test_id', 'user_id', name='_group_test_user_uc')
    )
    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participations_approved'), ['approved'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participations_approved'))

    op.drop_table('participations')
    with op.batch_alter_table('group_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_tests_status'))

    op.drop_table('group_tests')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_tg_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
